spring:
  sleuth:
    enabled: true
    stream:
      enabled: true
    sampler:
      percentage: 1.0
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181
      bindings:
        sleuth:
          destination: sleuth_topic
          binder: kafka

server:
  port: 8081

endpoints:
  restart:
    enabled: true

management:
  security:
    enabled: false

lifecycle-bean:
  enabled: true