spring:
  sleuth:
    enabled: true
    stream:
      enabled: true
    sampler:
      percentage: 1.0
  cloud:
    stream:
      kafka:
        binder:
          brokers: bingo-dev10-mgp-01.preprod.cloud.local.dub:9092
          zkNodes: bingo-dev10-mgp-01.preprod.cloud.local.dub:2181
      bindings:
        sleuth:
          destination: bingoblitz_rotelle_sleuth
          binder: kafka

server:
  port: 8081

endpoints:
  restart:
    enabled: true

management:
  security:
    enabled: false

lifecycle-bean:
  enabled: true